export const countries = {
  "DE": {
    "name": "Germany",
    "pass_through_rate": 0.78,
    "lag_min_days": 9,
    "lag_max_days": 11,
    "lag_midpoint_days": 10,
    "currency": "EUR",
    "usd_exchange_source": "ecb_daily",
    "notes": "High refinery capacity. VAT buffers some volatility."
  },
  "GB": {
    "name": "United Kingdom",
    "pass_through_rate": 0.82,
    "lag_min_days": 7,
    "lag_max_days": 9,
    "lag_midpoint_days": 8,
    "currency": "GBP",
    "usd_exchange_source": "ecb_daily",
    "notes": "Less govt intervention. Fast pass-through."
  },
  "US": {
    "name": "United States",
    "pass_through_rate": 0.88,
    "lag_min_days": 5,
    "lag_max_days": 8,
    "lag_midpoint_days": 6,
    "currency": "USD",
    "usd_exchange_source": "none",
    "notes": "Highly competitive. Fastest pass-through globally."
  },
  "DEFAULT": {
    "name": "Default (Unlisted Country)",
    "pass_through_rate": 0.75,
    "lag_min_days": 10,
    "lag_max_days": 14,
    "lag_midpoint_days": 12,
    "currency": "USD",
    "usd_exchange_source": "ecb_daily",
    "notes": "Fallback for any country not in this file."
  }
}
export const COUNTRIES = {
  DE: {
    name: "Germany",
    pass_through_rate: 0.78,
    lag_min_days: 9,
    lag_max_days: 11,
    lag_midpoint_days: 10,
    currency: "EUR",
    usd_exchange_source: "ecb_daily",
    notes: "High refinery capacity. VAT buffers some volatility.",
  },
  GB: {
    name: "United Kingdom",
    pass_through_rate: 0.82,
    lag_min_days: 7,
    lag_max_days: 9,
    lag_midpoint_days: 8,
    currency: "GBP",
    usd_exchange_source: "ecb_daily",
    notes: "Less govt intervention. Fast pass-through.",
  },
  FR: {
    name: "France",
    pass_through_rate: 0.74,
    lag_min_days: 10,
    lag_max_days: 14,
    lag_midpoint_days: 12,
    currency: "EUR",
    usd_exchange_source: "ecb_daily",
    notes: "High fixed fuel taxes cushion short-term crude swings.",
  },
  NL: {
    name: "Netherlands",
    pass_through_rate: 0.8,
    lag_min_days: 6,
    lag_max_days: 10,
    lag_midpoint_days: 8,
    currency: "EUR",
    usd_exchange_source: "ecb_daily",
    notes: "Rotterdam hub proximity enables rapid price adjustments.",
  },
  PL: {
    name: "Poland",
    pass_through_rate: 0.76,
    lag_min_days: 10,
    lag_max_days: 14,
    lag_midpoint_days: 12,
    currency: "PLN",
    usd_exchange_source: "ecb_daily",
    notes: "State-influenced refining margins moderate retail transmission.",
  },
  ES: {
    name: "Spain",
    pass_through_rate: 0.72,
    lag_min_days: 11,
    lag_max_days: 15,
    lag_midpoint_days: 13,
    currency: "EUR",
    usd_exchange_source: "ecb_daily",
    notes: "Distribution logistics introduce a slight transmission buffer.",
  },
  IT: {
    name: "Italy",
    pass_through_rate: 0.7,
    lag_min_days: 12,
    lag_max_days: 16,
    lag_midpoint_days: 14,
    currency: "EUR",
    usd_exchange_source: "ecb_daily",
    notes: "Heavy excise structure moderates percentage pass-through.",
  },
  US: {
    name: "United States",
    pass_through_rate: 0.88,
    lag_min_days: 5,
    lag_max_days: 8,
    lag_midpoint_days: 6,
    currency: "USD",
    usd_exchange_source: "none",
    notes: "Highly competitive. Fastest pass-through globally.",
  },
  CA: {
    name: "Canada",
    pass_through_rate: 0.85,
    lag_min_days: 6,
    lag_max_days: 9,
    lag_midpoint_days: 7,
    currency: "CAD",
    usd_exchange_source: "market_rate",
    notes: "Integrated with US spot markets with regional provincial tax variations.",
  },
  AU: {
    name: "Australia",
    pass_through_rate: 0.86,
    lag_min_days: 10,
    lag_max_days: 16,
    lag_midpoint_days: 13,
    currency: "AUD",
    usd_exchange_source: "market_rate",
    notes: "Retail fuel price cycles across major metros cause lag variations.",
  },
  SA: {
    name: "Saudi Arabia",
    pass_through_rate: 0.35,
    lag_min_days: 20,
    lag_max_days: 35,
    lag_midpoint_days: 28,
    currency: "SAR",
    usd_exchange_source: "market_rate",
    notes: "State-regulated domestic fuel pricing cap limits market pass-through.",
  },
  AE: {
    name: "UAE",
    pass_through_rate: 0.62,
    lag_min_days: 20,
    lag_max_days: 31,
    lag_midpoint_days: 25,
    currency: "AED",
    usd_exchange_source: "market_rate",
    notes: "Fuel Price Committee resets prices monthly based on global benchmarks.",
  },
  IN: {
    name: "India",
    pass_through_rate: 0.68,
    lag_min_days: 14,
    lag_max_days: 22,
    lag_midpoint_days: 18,
    currency: "INR",
    usd_exchange_source: "rbi_daily",
    notes: "OMC dynamic pricing adjusted for excise, VAT, and administrative smoothing.",
  },
  SG: {
    name: "Singapore",
    pass_through_rate: 0.91,
    lag_min_days: 4,
    lag_max_days: 7,
    lag_midpoint_days: 5,
    currency: "SGD",
    usd_exchange_source: "market_rate",
    notes: "Primary regional trading and refining hub; near-immediate price tracking.",
  },
  JP: {
    name: "Japan",
    pass_through_rate: 0.8,
    lag_min_days: 10,
    lag_max_days: 14,
    lag_midpoint_days: 12,
    currency: "JPY",
    usd_exchange_source: "market_rate",
    notes: "Government subsidies and refinery pricing schedules temper sudden spikes.",
  },
  KR: {
    name: "South Korea",
    pass_through_rate: 0.79,
    lag_min_days: 9,
    lag_max_days: 13,
    lag_midpoint_days: 11,
    currency: "KRW",
    usd_exchange_source: "market_rate",
    notes: "Competitive domestic refining with periodic fuel tax adjustments.",
  },
  BR: {
    name: "Brazil",
    pass_through_rate: 0.73,
    lag_min_days: 12,
    lag_max_days: 18,
    lag_midpoint_days: 15,
    currency: "BRL",
    usd_exchange_source: "market_rate",
    notes: "Petrobras commercial strategy and ethanol blending affect retail impact.",
  },
  ZA: {
    name: "South Africa",
    pass_through_rate: 0.77,
    lag_min_days: 20,
    lag_max_days: 32,
    lag_midpoint_days: 26,
    currency: "ZAR",
    usd_exchange_source: "market_rate",
    notes: "Regulated Basic Fuel Price (BFP) mechanism updated monthly.",
  },
  DEFAULT: {
    name: "Default (Unlisted Country)",
    pass_through_rate: 0.75,
    lag_min_days: 10,
    lag_max_days: 14,
    lag_midpoint_days: 12,
    currency: "USD",
    usd_exchange_source: "ecb_daily",
    notes: "Fallback baseline for countries outside the primary index.",
  },
};